### ISSUE TITLE
KeepassAnd is blank on external ChromeOS screens

### ISSUE THREAD

**Issue by trystant** [trystant/knowledgebase#29]
I'm running into this issue https://github.com/PhilippC/keepass2android/issues/272 on my Pixelbook.

**Comment by jeffmcneill** [comment]
Try to disable the anti-screenshot feature in settings.

**Comment by trystant** [comment]
I've obviated the need for this by using [Keeweb](https://keeweb.info/) to have a running instance that can be accessed from multiple platforms.
